version: '3'

services:
  test-db:
    image: postgres
    container_name: test_db
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: lyle
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lyle
    ports:
      - 5433:5432

  dev-db:
    image: postgres
    container_name: dev_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: lyle
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lyle
    ports:
      - 5434:5432

volumes:
  postgres_data:
